import { User } from "@/types/User";
import { Timestamp, collection, doc, setDoc } from "firebase/firestore";
import { faker } from "@faker-js/faker";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { auth, db } from "@/firebase/clientApp";

export const generateDummyUser = async (): Promise<void> => {
  console.log("I am running");
  const dummyTimestamp = Timestamp.fromDate(new Date());

  const user: User = {
    id: "",
    name: faker.person.fullName(),
    email: faker.internet.email(),
    password: faker.internet.password(),
    address: faker.location.streetAddress(),
    phone: faker.phone.number(),
    created_at: dummyTimestamp,
    updated_at: dummyTimestamp,
  };

  // Create user in Firebase Auth
  const userCredential = await createUserWithEmailAndPassword(auth, user.email, user.password);
  const userId = userCredential.user.uid;

  // Update user ID with the one generated by Firebase Auth
  user.id = userId;

  // Save user to Firestore
  await setDoc(doc(collection(db, "users"), user.id), user);

  console.log("Dummy user created:", user);
};
